title: cgswords
description: "A web blog for Cameron Swords"

url: http://cgswords.github.io/
port: 3000
highlighter: redcarpet2

permalink: /:year/:month/:day/:title.html
markdown: redcarpet

google_analytics: #

owner:
  name: Cameron Swords
  disqus_shortname: 
  twitter: CameronSwords
